feat(sourcing): support bundle products in default sourcing service
i-love-flamingo/flamingo-commerce pull request #453
Opened 2023-04-14 09:36 UTC by KarolNowakk

2023-04-14 15:09 UTC, IvanMaidurov commented on sourcing/domain/service.go
> +func (d *DefaultSourcingService) allocateBundleWithActiveChoices(ctx context.Context, itemQty int, productSourcestock map[string]map[Source]int, bundleProduct domain.BundleProductWithActiveChoices, d
very minor: you can place arguments on separate lines to make it easier to read

2023-04-14 15:09 UTC, IvanMaidurov commented on sourcing/domain/service.go
> +	productID := product.GetIdentifier()
I guess you don't need productID here anymore. You can validate product.GetIdentifier() directly and then not pass product id to d.allocateFromSources()

2023-04-17 13:53 UTC, carstendietrich requested changes
Please mention changes in Changelog.

2023-04-17 13:53 UTC, carstendietrich commented on sourcing/domain/service.go
> +	if decoratedItem.Product.Type() == domain.TypeBundle || decoratedItem.Product.Type() == domain.TypeConfigurableWithActiveVariant {
why cant we source configurable with active variant?

2023-04-17 13:53 UTC, carstendietrich commented on sourcing/domain/service.go
> +		return nil, productSourcestock, fmt.Errorf("error getting possible sources: %w", err)
maybe add the product identifier which we try to source for better errors

2023-04-21 12:15 UTC, carstendietrich requested changes

2023-04-21 12:15 UTC, carstendietrich commented on sourcing/domain/service.go
> +	if product.GetIdentifier() == "" {
maybe move that at the beginning of the func like the checks for type etc

2023-04-21 12:15 UTC, carstendietrich commented on sourcing/domain/service.go
> +func (d *DefaultSourcingService) allocateItem(
maybe rename to `allocateProduct`

2023-04-21 12:15 UTC, carstendietrich commented on sourcing/domain/service.go
> +func (d *DefaultSourcingService) allocateItemForProduct(
would name this just allocateItem

2023-04-24 15:08 UTC, carstendietrich requested changes

2023-04-25 11:14 UTC, carstendietrich approved these changes

2023-04-25 11:24 UTC, merged