feat(cart): add update bundle item mutation and service method
i-love-flamingo/flamingo-commerce pull request #493
Opened 2023-10-11 07:08 UTC by KarolNowakk

2023-10-12 11:02 UTC, ChristopherSchwab commented on cart/application/cartService.go
> +			return fmt.Errorf("delivery code not found by item, while updateing bundle %w", err)
```suggestion
			return fmt.Errorf("delivery code not found by item while updating bundle %w", err)
```

2023-10-12 11:02 UTC, ChristopherSchwab commented on cart/application/cartService.go
> +			return fmt.Errorf("error vaidating bundle update: %w", err)
```suggestion
			return fmt.Errorf("error validating bundle update: %w", err)
```

2023-10-12 13:17 UTC, ChristopherSchwab commented on cart/application/cartService.go
> +	product, err = cs.getSpecificProductType(ctx, product, item.VariantMarketPlaceCode, item.BundleConfig)
Should be updateCommand.BundleConfiguration, shouldnt it?

2023-10-12 14:39 UTC, carstendietrich requested changes

2023-10-12 14:39 UTC, carstendietrich commented on cart/application/cartService.go
> +			return fmt.Errorf("delivery code not found by item, while updating bundle %w", err)
```suggestion
			return fmt.Errorf("delivery code not found by item, while updating bundle: %w", err)
```

2023-10-12 14:39 UTC, carstendietrich commented on cart/application/cartService.go
> +	ErrProductNotTypeBundle            = errors.New("product not of type bundle with active choices")
```suggestion
	ErrProductNotTypeBundle            = errors.New("product not of type bundle")
```

2023-10-12 14:39 UTC, carstendietrich commented on cart/application/cartService.go
> +	product, err = cs.getBundleWithActiveChoices(ctx, product, item.VariantMarketPlaceCode, updateCommand.BundleConfiguration)
guess variant marketplace code makes only sense for configurables

2023-10-12 14:39 UTC, carstendietrich commented on cart/interfaces/graphql/mutationresolvers.go
> +func (r *CommerceCartMutationResolver) CommerceUpdateItemBundleConfig(ctx context.Context, itemID string, bundleConfig []*dto.ChoiceConfiguration) (*dto.DecoratedCart, error) {
integration test where are you?

2023-10-16 12:55 UTC, carstendietrich approved these changes

2023-10-16 13:03 UTC, merged